
include color.ini

enable_audio_bell no
font_family       JetBrainsMono Nerd Font
font_size         11
disable_ligatures never
font_features     +zero +onum +liga +calt
bold_font         auto
italic_font       auto
bold_italic_font  auto
cursor_trail      1
url_color         #fff
url_style         curly

tab_bar_edge        top
tab_bar_style       powerline
tab_powerline_style slanted

background_image        ~/.dotfiles/images/oneshot/video-game-oneshot-niko-oneshot-rowbot-oneshot-wallpaper-49e0289d714a9d3b8657780fa08176ad.jpg
background_image_layout cscaled
background_tint         0.92
