include themes/catppuccin_mocha.conf
include ${KITTY_OS}.conf

shell_integration enabled
enable_audio_bell no
font_family       JetBrainsMono Nerd Font
disable_ligatures never
font_features     +zero +onum +liga +calt
bold_font         auto
italic_font       auto
bold_italic_font  auto
cursor_trail      1
url_color         #fff
url_style         curly
# A setting to prevent low contrast between foreground and background colors.
text_fg_override_threshold 0

tab_bar_edge        top
tab_bar_style       powerline
tab_powerline_style slanted

background_image        ~/.dotfiles/images/oneshot/video-game-oneshot-niko-oneshot-rowbot-oneshot-wallpaper-49e0289d714a9d3b8657780fa08176ad.jpg
background_image_layout cscaled
background_tint         0.92

# Allow remote control
allow_remote_control yes
listen_on unix:/tmp/mykitty

# Enable the 'splits' layout as the primary layout.
enabled_layouts splits,stack,tall,fat,grid

map --new-mode prefix ctrl+s

map --mode prefix esc pop_keyboard_mode
map --mode prefix ctrl+s combine : pop_keyboard_mode : send_key ctrl+s

map ctrl+1 remote_control focus-tab --match index:0
map ctrl+2 remote_control focus-tab --match index:1
map ctrl+3 remote_control focus-tab --match index:2
map ctrl+4 remote_control focus-tab --match index:3
map ctrl+5 remote_control focus-tab --match index:4
map ctrl+6 remote_control focus-tab --match index:5
map ctrl+7 remote_control focus-tab --match index:6
map ctrl+8 remote_control focus-tab --match index:7
map ctrl+9 remote_control focus-tab --match index:8
map ctrl+0 remote_control focus-tab --match index:-1

map --mode prefix p combine : command_palette : pop_keyboard_mode
map --mode prefix r combine : load_config_file : kitten notify "Config reloaded" Config has been reloaded : pop_keyboard_mode

map kitty_mod+t launch --cwd current --type tab --location after

map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l

map ctrl+alt+h previous_tab
map ctrl+alt+l next_tab

map ctrl+alt+shift+h move_tab_backward
map ctrl+alt+shift+l move_tab_forward

# Remove your current neighboring_window and IS_NVIM maps, and replace with:
map ctrl+shift+j kitten split_window.py down
map ctrl+shift+k kitten split_window.py up
map ctrl+shift+h kitten split_window.py left
map ctrl+shift+l kitten split_window.py right 

# the 3 here is the resize amount, adjust as needed
map alt+j kitten relative_resize.py down  3
map alt+k kitten relative_resize.py up    3
map alt+h kitten relative_resize.py left  3
map alt+l kitten relative_resize.py right 3

map --when-focus-on var:IS_NVIM alt+j
map --when-focus-on var:IS_NVIM alt+k
map --when-focus-on var:IS_NVIM alt+h
map --when-focus-on var:IS_NVIM alt+l

map ctrl+g kitten hints --type=linenum --linenum-action=tab nvim +{line} {path}

action_alias kitty_scrollback_nvim kitten ~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
map kitty_mod+x kitty_scrollback_nvim
