font_size 11
map kitty_mod+x launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay /bin/zsh -c "NO_PLUGINS=1 nvim +$ +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set number relativenumber' +'$' -"
