[styles.battery]
high_battery_color = "#a6e3a1"
low_battery_color = "#f38ba8"
medium_battery_color = "#f9e2af"

[styles.cpu]
all_entry_color = "#f5e0dc"
avg_entry_color = "#eba0ac"
cpu_core_colors = [
    "#f38ba8",
    "#fab387",
    "#f9e2af",
    "#a6e3a1",
    "#74c7ec",
    "#cba6f7",
]

[styles.graphs]
graph_color = "#a6adc8"

[styles.graphs.legend_text]
color = "#a6adc8"

[styles.memory]
arc_color = "#89dceb"
cache_color = "#f38ba8"
gpu_colors = [
    "#74c7ec",
    "#cba6f7",
    "#f38ba8",
    "#fab387",
    "#f9e2af",
    "#a6e3a1",
]
ram_color = "#a6e3a1"
swap_color = "#fab387"

[styles.network]
rx_color = "#a6e3a1"
rx_total_color = "#89dceb"
tx_color = "#f38ba8"
tx_total_color = "#a6e3a1"

[styles.tables.headers]
color = "#f5e0dc"

[styles.widgets]
border_color = "#585b70"
selected_border_color = "#f5c2e7"

[styles.widgets.disabled_text]
color = "#1e1e2e"

[styles.widgets.selected_text]
bg_color = "#cba6f7"
color = "#11111b"

[styles.widgets.text]
color = "#cdd6f4"

[styles.widgets.widget_title]
color = "#f2cdcd"
