" Enable syntax highlighting
syntax on

" Set the number of spaces to 4 for one tab.
set shiftwidth=4
" Removing `shiftwidth` spaces when backspacing.
set smarttab
" Inserting tabs as spaces
set expandtab
" Enable auto-indentation
set autoindent


" Enable line numbers
set number
" Enable relative line numbers
set relativenumber

let mapleader = " "
nnoremap <leader>so :so<cr>

" Plugins

call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end() 

" Catppuccin 
colorscheme catppuccin_mocha
let g:airline_theme = 'catppuccin_mocha'
