#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

WEATHER_LABEL_COLOR="$blue"
WEATHER_BACKGROUND_BORDER_COLOR="$blue"

sketchybar --add item weather_spacer_right right \
           --set      weather_spacer_right \
                      background.drawing=off

sketchybar --add item weather right \
           --set      weather \
                      background.drawing=off \
                      label.color="$WEATHER_LABEL_COLOR" \
                      label.padding_left=0 \
                      label.padding_right=0 \
                      update_freq=1800 \
                      script="$PLUGIN_DIR/weather.sh"

sketchybar --add item weather_spacer_left right \
           --set      weather_spacer_left \
                      background.drawing=off

sketchybar --add bracket weather_bracket weather_spacer_left weather weather_spacer_right \
           --set         weather_bracket \
                         background.border_color="$WEATHER_BACKGROUND_BORDER_COLOR" \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH" 