local apps = require('modules.programs')

hl.on('hyprland.start', function()
    hl.exec_cmd(apps.terminal)
    hl.exec_cmd(apps.browser)
    hl.exec_cmd('nm-applet')
    hl.exec_cmd('quickshell')
    hl.exec_cmd('hypridle')
    hl.exec_cmd('awww-daemon')
    hl.exec_cmd('awww img ' .. os.getenv('HOME') .. '/.dotfiles/images/hollow_knight/1184118.jpg')
end)
