[mgr]
show_hidden = true
show_symlink = true

[[opener.edit]]
block = true
for = "unix"
run = "$EDITOR %s"

[[opener.edit]]
block = true
for = "windows"
run = "%EDITOR% %s"

[[opener.open]]
desc = "Open with the default program"
for = "unix"
run = "xdg-open %s"

[[opener.open]]
desc = "Open with the default program"
for = "macos"
run = "open %s"

[[opener.play]]
orphan = true
run = "mpv %s"

[preview]
wrap = "yes"

[plugin]
prepend_previewers = [
  { url = '*.typ', run = 'preview-typst' },
]

prepend_preloaders = [
  { url = '*.typ', run = 'preview-typst' },
]

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"
