[mgr]
show_hidden = true
show_symlink = true

[[opener.edit]]
block = true
for = "unix"
run = "$EDITOR %s"

[[opener.edit]]
block = true
for = "windows"
run = "%EDITOR% %s"

[[opener.open]]
desc = "Open with the default program"
for = "unix"
run = "xdg-open %s"

[[opener.open]]
desc = "Open with the default program"
for = "macos"
run = "open %s"

[[opener.play]]
orphan = true
run = "mpv %s"

[preview]
wrap = "yes"
