[aliases]
abd = ["abandon"]
b = ["bookmark"]
df = ["diff"]
ds = ["describe"]
dfp = ["diff", "-r", "@-"]
f = ["file"]
g = ["git"]
h = ["help"]
lg = ["log"]
rvt = ["revert", "--insert-after", "@-", "-r"]
lga = ["log-all"]
ll = ["log", "--reversed"]
log-all = ["log", "-r", "all()"]
n = ["new"]
prune-divergent = ["abandon", "'divergent():: ~ ::@'"]
show-last = ["show", "-r", "@-"]
sl = ["show-last"]

[colors]
commit_id = "green"
"working_copy commit_id" = { underline = true }
"working_copy change_id" = { underline = true }

[fsmonitor]
backend = "watchman"

[git]
abandon-unreachable-commits = true
# Don't accidentally push `tmp` bookmark
private-commits = "present(tmp)"

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]

[merge-tools.nvim]
diff-args = ["-d", "$left", "$right"]
edit-args = ["-d", "$left", "$right"]
merge-args = ["-d", "$left", "$output", "$right"]

[merge-tools.nvim-ext]
diff-args = ["-c", "DiffEditor $left $right $output"]
edit-args = ["-c", "DiffEditor $left $right $output"]
merge-args = ["-c", "DiffEditor $left $right $output"]
program = "nvim"

[revsets]
log = "trunk()..@ | @..trunk() | trunk() | @:: | fork_point(trunk() | @) | ancestors(@, 10) | ancestors(tracked_remote_bookmarks().., 2)"
bookmark-advance-from = 'heads(::to & bookmarks())'  # The closest bookmarks
bookmark-advance-to = '(@ - empty()) | parents(@ & empty())' # Current working copy, or the parent of it if empty

[revset-aliases]
HEAD = "@-"
orphans = "mutable() & all() ~ ::@"
all-orphans = "all() ~ ::@"

[snapshot]
auto-update-stale = true

[templates]
draft_commit_description = "concat(\n  description,\n  surround(\n    \"\\nJJ: Changes:\\n\",\n    \"\",\n    indent(\"JJ: \", diff.stat(72)),\n  ),\n  surround(\"\\nJJ: Diff:\\n\", \"\", indent(\"JJ: \", diff.git(4)))\n)\n"
duplicate_description = '''
concat(
  description.trim_end(),
  "\n\n(cherry picked from commit ",
  commit_id,
  ")\n"
)
'''
new_description = '''
if(parents.len() > 1,
  "Merge " ++ parents.skip(1).map(|p| if(
    p.bookmarks(),
    p.bookmarks().first().name(),
    p.change_id().shortest(8)
  )).join(", ") ++ " into " ++ if(
    parents.first().bookmarks(),
    parents.first().bookmarks().first().name(),
    parents.first().change_id().shortest(8)
  ) ++ "\n",
  ""
)
'''

[ui]
color = "auto"
default-command = ["log", "--reversed"]
diff-editor = "nvim-ext"
editor = "nvim"
pager = "delta"

[user]
email = "33772093+larpios@users.noreply.github.com"
name = "larpios"
