#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

BATTERY_LABEL_COLOR="$yellow"
BATTERY_BACKGROUND_BORDER_COLOR="$yellow"

sketchybar --add item battery_spacer_right right \
           --set      battery_spacer_right \
                      background.drawing=off

sketchybar --add item battery right \
           --set      battery \
                      background.drawing=off \
                      label.color="$BATTERY_LABEL_COLOR" \
                      label.padding_left=0 \
                      label.padding_right=0 \
                      update_freq=20 \
                      script="$PLUGIN_DIR/battery.sh"

sketchybar --add item battery_spacer_left right \
           --set      battery_spacer_left \
                      background.drawing=off

sketchybar --add bracket battery_bracket battery_spacer_left battery battery_spacer_right \
           --set         battery_bracket \
                         background.border_color="$BATTERY_BACKGROUND_BORDER_COLOR" \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH" 