#!/usr/bin/env bash

SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
DATA_DIR="$XDG_DATA_HOME/bash/"

export BASH_CONFIG_DIR="${SCRIPT_DIR:-"$HOME/.config/bash/"}"
export BASH_CONFIG_PATH="${SCRIPT_PATH:-"$HOME/.config/bash/bashrc"}"
export BASH_DATA_DIR="${DATA_DIR:-"$HOME/.local/share/bash/"}"

# Ensure data dir exists
mkdir -p "${BASH_DATA_DIR}"

source "${BASH_CONFIG_DIR}/functions.sh"
source "${BASH_CONFIG_DIR}/aliases.sh"
source "${BASH_CONFIG_DIR}/external.sh"
source "${BASH_CONFIG_DIR}/plugins.sh"
