export def query [
    expression: string
    --language (-l): string@"nu-complete language" = "Any"
    --source-language (-s): string@"nu-complete source-language" = "English"
    --raw (-r) # Whether to skip processing
] : nothing -> record {
    if ($expression | is-empty) {
        error make {
            msg: 'expression cannot be empty'
            labels: [
                {
                    text: 'empty',
                    span: (metadata $expression).span
                }
            ]
        }
    }

    if not ($language in (nu-complete language)) {
        error make {
            msg: 'provided language is not supported'
            labels: [
                {
                    text: 'unsupported language',
                    span: (metadata $language).span
                }
            ]
        }
    }

    let p1 = $expression | str substring 0..0
    let p2 = $expression | str substring 0..1
    let dict = match $source_language {
        "Chinese"        => "zhwiktionary"
        "French"         => "frwiktionary"
        "German"         => "dewiktionary"
        "Russian"        => "ruwiktionary"
        "Spanish"        => "eswiktionary"
        "Polish"         => "plwiktionary"
        "Japanese"       => "jawiktionary"
        "Simple English" => "simplewiktionary"
        "Dutch"          => "nlwiktionary"
        "Korean"         => "kowiktionary"
        "Portuguese"     => "ptwiktionary"
        "Italian"        => "itwiktionary"
        "Thai"           => "thwiktionary"
        "Kurdish"        => "kuwiktionary"
        "Greek"          => "elwiktionary"
        "Turkish"        => "trwiktionary"
        "Indonesian"     => "idwiktionary"
        "Malay"          => "mswiktionary"
        "Vietnamese"     => "viwiktionary"
        "Czech"          => "cswiktionary"
        _                => "dictionary"
    }
    let lang = if $language == "Any" {
        "All languages combined"
    } else {
        $language
    }
    let url = $"https://kaikki.org/($dict)/($lang)/meaning/($p1)/($p2)/($expression).jsonl" | url encode

    let raw_response = try {
        http $url
    } catch { |err|
        let err_raw = ($err.json | from json | get labels.text | last)
        if $err_raw =~ '404' {
            print $"(ansi yellow)No entry for `($expression)`(ansi reset)"
            return
        } else {
            error make $err
        }
        return
    }
    let data = $raw_response | decode | lines | each { from json }

    if $raw {
        $data
    } else {
        let processed = $data
        | select senses pos word lang 
        | flatten 
        | group-by lang 
        | transpose lang entries
        | update entries { |lang_row|
            $lang_row.entries
            | group-by pos
            | transpose pos items
            | update items { |pos_row|
                $pos_row.items | each { |row|
                    {
                        senses: ($row.senses.glosses? | default [] | flatten)
                        examples: (try { $row.senses.examples.text } catch { [] })
                    }
                }
                # $pos_row.items | get senses.glosses? | flatten
            }
            | transpose -rd
        }
        | transpose -rd

        $processed
    }
}

def "nu-complete language" [] {
    [
        "Any"
        "English" 
        "Latin" 
        "Spanish" 
        "Italian" 
        "German" 
        "Portuguese" 
        "Russian" 
        "French" 
        "Chinese" 
        "Swedish" 
        "Finnish" 
        "Polish" 
        "Galician" 
        "Japanese" 
        "Catalan" 
        "Dutch" 
        "Latvian" 
        "Romanian" 
        "Esperanto" 
        "Greek" 
        "Mandarin" 
        "Translingual" 
        "Arabic" 
        "Serbo-Croatian" 
        "Hungarian" 
        "Old English" 
        "Czech" 
        "Ancient Greek" 
        "Norwegian Bokmål" 
        "Ukrainian" 
        "Korean" 
        "Macedonian" 
        "Norwegian Nynorsk" 
        "Bulgarian" 
        "Danish" 
        "Middle English" 
        "Vietnamese" 
        "Turkish" 
        "Hindi" 
        "Indonesian" 
        "Tagalog" 
        "Irish" 
        "Asturian" 
        "Welsh" 
        "Lithuanian" 
        "Icelandic" 
        "Albanian" 
        "Sanskrit" 
        "Georgian" 
        "Armenian" 
        "Telugu" 
        "Tamil" 
        "Persian" 
        "Thai" 
        "Gothic" 
        "Cebuano" 
        "Scottish Gaelic" 
        "Swahili" 
        "Hebrew" 
        "Ido" 
        "Maltese" 
        "Azerbaijani" 
        "Slovak" 
        "Malay" 
        "Navajo" 
        "Malayalam" 
        "Urdu" 
        "Estonian" 
        "Punjabi" 
        "Old Norse" 
        "Yiddish" 
        "Khmer" 
        "Bengali" 
        "Kazakh" 
        "Basque" 
        "Ottoman Turkish" 
        "Burmese" 
        "Old Armenian" 
        "Pali" 
        "Faroese" 
        "Norman" 
        "Assyrian Neo-Aramaic" 
        "Old French" 
        "Afrikaans" 
        "Ingrian" 
        "Luxembourgish" 
        "Cantonese" 
        "Pannonian Rusyn" 
        "Belarusian" 
        "Gujarati" 
        "Slovene" 
        "Central Bikol" 
        "Old Irish" 
        "Mongolian" 
        "Classical Syriac" 
        "Ladin" 
        "Egyptian" 
        "Northern Kurdish" 
        "Yoruba" 
        "Occitan" 
        "Proto-Germanic" 
        "Javanese" 
        "Northern Sami" 
        "Old Polish" 
        "Scots" 
        "Proto-West Germanic" 
        "Marathi" 
        "Proto-Slavic" 
        "West Circassian" 
        "Hawaiian" 
        "Livonian" 
        "Assamese" 
        "Old Church Slavonic" 
        "Aromanian" 
        "Cimbrian" 
        "Cornish" 
        "Crimean Tatar" 
        "Khiamniungan Naga" 
        "Venetan" 
        "Old Czech" 
        "Manx" 
        "Classical Nahuatl" 
        "Middle French" 
        "Māori" 
        "Plautdietsch" 
        "Yakut" 
        "Uyghur" 
        "Zulu" 
        "Bashkir" 
        "Uzbek" 
        "Lower Sorbian" 
        "Votic" 
        "Tibetan" 
        "Kyrgyz" 
        "Sicilian" 
        "Odia" 
        "Tajik" 
        "Volapük" 
        "South Levantine Arabic" 
        "Interlingua" 
        "Middle Dutch" 
        "Malagasy" 
        "Old High German" 
        "Sundanese" 
        "Kashubian" 
        "Proto-Finnic" 
        "Laz" 
        "West Frisian" 
        "Coptic" 
        "Ushojo" 
        "Xhosa" 
        "Kannada" 
        "Silesian" 
        "Quechua" 
        "Northern Yukaghir" 
        "Old Javanese" 
        "Palula" 
        "Lower Tanana" 
        "Zhuang" 
        "Yola" 
        "Veps" 
        "Emilian" 
        "Tarifit" 
        "Hijazi Arabic" 
        "Lao" 
        "Ladino" 
        "East Central German" 
        "Pennsylvania German" 
        "Shan" 
        "Manchu" 
        "Sumerian" 
        "Greenlandic" 
        "Walloon" 
        "Nepali" 
        "Low German" 
        "Aramaic" 
        "Bavarian" 
        "Franco-Provençal" 
        "Tocharian B" 
        "Moksha" 
        "Limburgish" 
        "Prakrit" 
        "Old Saxon" 
        "Hokkien" 
        "Moroccan Arabic" 
        "Hunsrik" 
        "Hausa" 
        "Chichewa" 
        "Ligurian" 
        "Romansh" 
        "Friulian" 
        "Ye'kwana" 
        "Amharic" 
        "Hiligaynon" 
        "Breton" 
        "Saterland Frisian" 
        "Kashmiri" 
        "Dhivehi" 
        "Unami" 
        "Proto-Indo-European" 
        "Haitian Creole" 
        "Afar" 
        "Ainu" 
        "Tok Pisin" 
        "Fula" 
        "Sranan Tongo" 
        "Turkmen" 
        "Cherokee" 
        "Old Dutch" 
        "Eastern Mari" 
        "Alemannic German" 
        "Old Tupi" 
        "Kapampangan" 
        "Akkadian" 
        "Khalaj" 
        "Southern Altai" 
        "Pashto" 
        "Kumyk" 
        "Mokilese" 
        "Sirenik" 
        "Ojibwe" 
        "Tatar" 
        "Middle High German" 
        "Tangut" 
        "Old Swedish" 
        "Proto-Samic" 
        "Kildin Sami" 
        "Proto-Celtic" 
        "Marshallese" 
        "Lingala" 
        "Ilocano" 
        "Balinese" 
        "Aragonese" 
        "Neapolitan" 
        "Central Nahuatl" 
        "Swazi" 
        "Romagnol" 
        "Old Galician-Portuguese" 
        "Upper Sorbian" 
        "Tày" 
        "Ternate" 
        "Senhaja de Srair" 
        "Makasar" 
        "Vilamovian" 
        "Norwegian" 
        "Sardinian" 
        "Mon" 
        "Abkhaz" 
        "Gagauz" 
        "Woiwurrung" 
        "North Frisian" 
        "Udmurt" 
        "Komi-Zyrian" 
        "Tausug" 
        "Iban" 
        "Sindhi" 
        "Old Spanish" 
        "Jeju" 
        "Chuvash" 
        "Central Kurdish" 
        "Ubykh" 
        "Konkani" 
        "Kikuyu" 
        "Northern Mansi" 
        "Salar" 
        "Sinhalese" 
        "Kabuverdianu" 
        "Proto-Turkic" 
        "Phuthi" 
        "White Hmong" 
        "Dalmatian" 
        "Erzya" 
        "Egyptian Arabic" 
        "Karelian" 
        "Slovincian" 
        "Zazaki" 
        "Northern Altai" 
        "Sikkimese" 
        "East Circassian" 
        "Mapudungun" 
        "Chickasaw" 
        "S'gaw Karen" 
        "Central Franconian" 
        "Romani" 
        "San Juan Quiahije Chatino" 
        "Tashelhit" 
        "Okinawan" 
        "Ahtna" 
        "Chechen" 
        "Tokelauan" 
        "Garo" 
        "Papiamentu" 
        "Maranao" 
        "Old East Slavic" 
        "Somali" 
        "Lule Sami" 
        "Middle Korean" 
        "Magahi" 
        "Mauritian Creole" 
        "Sylheti" 
        "Corsican" 
        "North Levantine Arabic" 
        "Piedmontese" 
        "Ossetian" 
        "Manipuri" 
        "Oromo" 
        "Mingrelian" 
        "West Makian" 
        "Tumbuka" 
        "Ugaritic" 
        "Macanese" 
        "Tuvan" 
        "Santali" 
        "Lombard" 
        "Ket" 
        "Bambara" 
        "Kankanaey" 
        "Tigrinya" 
        "Mizo" 
        "Middle Irish" 
        "Lakota" 
        "Old Anatolian Turkish" 
        "Chuukese" 
        "Inupiaq" 
        "Fala" 
        "Amis" 
        "Gulf Arabic" 
        "Choctaw" 
        "Proto-Indo-Iranian" 
        "Karao" 
        "Lushootseed" 
        "Tooro" 
        "Ludian" 
        "Kavalan" 
        "Ge'ez" 
        "Old Georgian" 
        "Jamaican Creole" 
        "Gun" 
        "Istriot" 
        "Ewe" 
        "Proto-Italic" 
        "Old Ruthenian" 
        "Waray-Waray" 
        "Nivkh" 
        "Proto-Malayo-Polynesian" 
        "Urak Lawoi'" 
        "Louisiana Creole" 
        "Kalmyk" 
        "Gamilaraay" 
        "Ghomala'" 
        "Proto-Samoyedic" 
        "Wolof" 
        "Central Atlas Tamazight" 
        "Central Huasteca Nahuatl" 
        "Proto-Bantu" 
        "Proto-Brythonic" 
        "Aghwan" 
        "Livvi" 
        "Even" 
        "Old Slovak" 
        "Rwanda-Rundi" 
        "Lü" 
        "Võro" 
        "Yucatec Maya" 
        "Hamer-Banna" 
        "Old Occitan" 
        "Mohawk" 
        "Tetum" 
        "Sassarese" 
        "Sakizaya" 
        "Mirandese" 
        "Dupaningan Agta" 
        "Evenki" 
        "Chagatai" 
        "Cubeo" 
        "Ingush" 
        "Old Frisian" 
        "Southern Ndebele" 
        "Sotho" 
        "Old Japanese" 
        "Eastern Huasteca Nahuatl" 
        "Lindu" 
        "Proto-Uralic" 
        "Skolt Sami" 
        "Murui Huitoto" 
        "Tarantino" 
        "Buryat" 
        "Latgalian" 
        "Acehnese" 
        "Antigua and Barbuda Creole English" 
        "Polabian" 
        "Nanai" 
        "Betawi" 
        "Fijian" 
        "Yogad" 
        "Yurok" 
        "Inari Sami" 
        "Nheengatu" 
        "Bourguignon" 
        "Samoan" 
        "Avar" 
        "Kalasha" 
        "Ao" 
        "Old Persian" 
        "Tlingit" 
        "Tetelcingo Nahuatl" 
        "Atayal" 
        "Nupe" 
        "Mycenaean Greek" 
        "Achang" 
        "Shona" 
        "Hanunoo" 
        "Taos" 
        "Baluchi" 
        "Old Uyghur" 
        "Anguthimri" 
        "Nǀuu" 
        "Proto-Ryukyuan" 
        "Saanich" 
        "Proto-Japonic" 
        "Tocharian A" 
        "Cahuilla" 
        "Inuktitut" 
        "Pite Sami" 
        "Middle Armenian" 
        "Northern Ndebele" 
        "Sambali" 
        "Khakas" 
        "Kurtöp" 
        "Tai Nüa" 
        "Mariupol Greek" 
        "Tundra Nenets" 
        "Svan" 
        "Proto-Balto-Slavic" 
        "Brunei Malay" 
        "Western Apache" 
        "Dakota" 
        "Bangi" 
        "Proto-Sino-Tibetan" 
        "Cypriot Arabic" 
        "Proto-Permic" 
        "Old Turkic" 
        "Bats" 
    ]
}

def "nu-complete source-language" [] {
    [
        "English"
        "Chinese"
        "French"
        "German"
        "Russian"
        "Spanish"
        "Polish"
        "Japanese"
        "Simple English"
        "Dutch"
        "Korean"
        "Portuguese"
        "Italian"
        "Thai"
        "Kurdish"
        "Greek"
        "Turkish"
        "Indonesian"
        "Malay"
        "Vietnamese"
        "Czech"
    ]
}

