format = """
$hostname\
$directory\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$hg_branch\
$docker_context\
$custom\
$sudo\

$fill\

${custom.jj}\
$git_branch\
$git_status\
$git_commit\
$cmd_duration\
$time\
$status\
$os\
$container\
$shell\
$line_break\
$character
"""
add_newline = false

palette = "catppuccin_mocha"

[hostname]
ssh_only = true
format = "[](fg:base bg:none)[█](fg:text bg:base)[$ssh_symbol$hostname](bold bg:text)[](fg:text bg:none) "
disabled = false

[sudo]
symbol = " "
style = "fg:text bg:base"
format = " [](fg:maroon bg:none)[$symbol](bold fg:base bg:maroon)[](fg:maroon bg:none) "
disabled = false

[directory]
format = "[](fg:base bg:none)[$path]($style)[█](fg:base bg:base)[](fg:blue bg:base)[ ](fg:base bg:blue)[](fg:blue bg:none)"
style = "fg:text bg:base bold"
truncation_length = 3
truncate_to_repo = true
read_only = " "

[character]
success_symbol = "[ ](blue bold)"
error_symbol = "[ ](red bold)"

[line_break]
disabled = false

[time]
disabled = false
style = "fg:text bg:base"
format = "[](fg:base bg:none)[$time]($style)[█](fg:base bg:none)[](fg:flamingo bg:none)[󱑆 ](fg:base bg:flamingo)[](fg:flamingo bg:none)"

[fill]
symbol = " "
style = "bold green"

[cmd_duration]
min_time = 1
format = "[](fg:base bg:none)[$duration]($style)[](fg:base bg:base)[](fg:mauve bg:base)[󱎫 ](fg:base bg:mauve)[](fg:mauve bg:none)"
show_notifications = true
disabled = false
style = "fg:text bg:base bold"

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]

[git_branch]
format = "[](fg:base bg:none)[$branch]($style)[](fg:base bg:base)[](fg:green bg:base)[](fg:base bg:green)[](fg:green bg:none) "
style = "fg:text bg:base"
symbol = " "

[git_status]
format = "[](fg:base bg:none)[$all_status$ahead_behind]($style)[](fg:base bg:base)[](fg:sky bg:base)[ ](fg:base bg:sky)[](fg:sky bg:none) "
style = "fg:text bg:base"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = " 󰄸 "
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = " ${count}"

[git_commit]
format = '[\($hash\)]($style) [\($tag\)]($style)'
style = "green"

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = [
    "docker-compose.yml",
    "docker-compose.yaml",
    "Dockerfile",
]
detect_folders = []
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "
disabled = true

[hg_branch]
symbol = " "

[java]
symbol = " "
disabled = true

[julia]
symbol = " "

[haskell]
disabled = true
symbol = "λ "

[nix_shell]
symbol = " "

[perl]
disabled = true
symbol = " "

[php]
symbol = " "

[python]
disabled = true
symbol = " "
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = [
    "./venv/bin/python",
    "python",
    "python3",
    "python2",
]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
disabled = true
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
disabled = true
format = "via [ Node.js $version](bold green) "
detect_files = [
    "package.json",
    ".node-version",
]
detect_folders = ["node_modules"]

[c]
disabled = true

[cmake]
disabled = true

[package]
disabled = true

[lua]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
