#!/usr/bin/env zsh
# shellcheck shell=zsh disable=SC3028,SC3054

export CURRENT_SHELL="sh"

SCRIPT_PATH=""
if [ "$BASH_VERSION" != "" ]; then
    CURRENT_SHELL="bash"
    SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
elif [ "$ZSH_VERSION" != "" ]; then
    CURRENT_SHELL="zsh"
    SCRIPT_PATH="$(realpath "${(%):-%x}")"
else
    SCRIPT_PATH="$(realpath "$0")"
fi

SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
DATA_DIR="${XDG_DATA_HOME:-"$HOME/.local/share"}"

export SH_CONFIG_DIR="${SCRIPT_DIR:-"$HOME/.config/sh"}"
export SH_CONFIG_PATH="${SCRIPT_PATH:-"$HOME/.config/sh/shrc"}"
export SH_DATA_DIR="${DATA_DIR}/sh/"

# Ensure data dir exists
mkdir -p "$SH_DATA_DIR"

. "${SH_CONFIG_DIR}/functions.sh"
. "${SH_CONFIG_DIR}/exports.sh"
. "${SH_CONFIG_DIR}/aliases.sh"
. "${SH_CONFIG_DIR}/external.sh"

unset SCRIPT_PATH
unset SCRIPT_DIR
unset DATA_DIR
